### ISSUE TITLE
如何设置树形表格默认全部展开？

### ISSUE THREAD

**Issue by MikuBlog** [zhjing1019/ComplexGrid#1]
如题

**Comment by zhjing1019** [comment]
这个组件暂时还没有默认全部展开的事件，目前是默认展开一级节点，我明天之前更新一下，抛一个事件让可以默认展开全部

**Comment by zhjing1019** [comment]
你好，我更新了ComplexGrid,版本为1.1.1。
可以给组件添加属性 :isExpandAll="true"，就可以设置树形表格全部展开，
` <sum-grid
      ref="treeGrid1"
      :fields="treeGridJson.fields"
      :data.sync="treeGridJson.data"
      :checkable="true"
      :isTree="true"
      :empty="empty"
      style="height: 300px"
      @clickFirst="testClick"
      @dataPage="dataPage"
      @dragStart="dragstart"
      @dragEnd="dragendTree"
      @checkboxClick="checkboxClick"
      @checkAllClick="checkAllClick"
      :loadState="loadState"
      :isDrag="true"
      :isExpandAll="true"
    >
    </sum-grid>`
也可以设置某一行数据进行展开和折叠,可以调用事件makeTreeExpand(id, isExpand),id为树的节点id，isExpand为Boolean值，true为展开，false为收起。
`this.$refs[ref].makeTreeExpand(id, true)`
